"""Rebuild data-set level index files from every client's Answer_Key.json.

Outputs (repo root of the data set):
  answer_key/summary.csv        one row per client with the key 1040 lines
  answer_key/all_gotchas.jsonl  every rubric item, one per line (for eval harnesses)
  CLIENT_INDEX.md               human-readable roster + gotcha counts + key numbers
"""
import csv
import glob
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, ".."))


def run():
    keys = sorted(glob.glob(os.path.join(ROOT, "clients", "*", "2025", "*_Answer_Key.json")))
    rows, gl = [], []
    for k in keys:
        try:
            d = json.load(open(k))
        except Exception as e:  # keep building even if one client is mid-write
            print("skip", k, e)
            continue
        s = d.get("form_1040_summary", {})
        rows.append({
            "client_id": d["client_id"], "client": d["client"], "filing_status": d.get("filing_status"),
            "state": d.get("facts_summary", {}).get("residence", ""),
            "agi_11": s.get("11"), "deduction_12e": s.get("12e"), "deduction_type": d.get("deduction_type"),
            "qbi_13a": s.get("13a"), "sch1a_13b": s.get("13b"), "taxable_income_15": s.get("15"),
            "tax_16": s.get("16"), "total_tax_24": s.get("24"), "payments_33": s.get("33"),
            "refund": d.get("refund"), "balance_due": d.get("balance_due"), "gotchas": len(d.get("gotchas", [])),
            "folder": os.path.relpath(os.path.dirname(os.path.dirname(k)), ROOT),
        })
        for g in d.get("gotchas", []):
            gl.append(dict(client_id=d["client_id"], **g))
    os.makedirs(os.path.join(ROOT, "answer_key"), exist_ok=True)
    if rows:
        with open(os.path.join(ROOT, "answer_key", "summary.csv"), "w", newline="") as fh:
            w = csv.DictWriter(fh, fieldnames=list(rows[0].keys()))
            w.writeheader()
            w.writerows(rows)
    with open(os.path.join(ROOT, "answer_key", "all_gotchas.jsonl"), "w") as fh:
        for g in gl:
            fh.write(json.dumps(g) + "\n")
    md = ["# Client Index - Project Evergreen Synthetic Data Set v1 (TY2025)", "",
          "*Auto-generated by `generator/summarize.py` from each client's Answer Key. Synthetic data.*", "",
          "| ID | Client | Status | Residence | AGI | Taxable income | Total tax | Refund | Balance due | Gotchas | Folder |",
          "|---|---|---|---|---:|---:|---:|---:|---:|---:|---|"]
    f = lambda x: f"{x:,}" if isinstance(x, (int, float)) else (x or "")
    for r in rows:
        md.append(f"| {r['client_id']} | {r['client']} | {r['filing_status']} | {r['state']} | {f(r['agi_11'])} | "
                  f"{f(r['taxable_income_15'])} | {f(r['total_tax_24'])} | {f(r['refund'])} | {f(r['balance_due'])} | "
                  f"{r['gotchas']} | [`{r['folder']}`]({r['folder']}) |")
    # gotcha by procedure section
    by = {}
    for g in gl:
        sec = g.get("procedure_section", "").split(" - ")[0].split(" (")[0].strip() or "Other"
        by.setdefault(sec, []).append(g["id"])
    md += ["", f"## Gotchas by procedure area ({len(gl)} total)", "", "| Procedure area | Count | Rubric IDs |", "|---|---:|---|"]
    for sec in sorted(by, key=lambda s: (-len(by[s]), s)):
        md.append(f"| {sec} | {len(by[sec])} | {', '.join(by[sec])} |")
    md += ["", "## All gotchas", "", "| ID | Title | Procedure section | Difficulty |", "|---|---|---|---|"]
    for g in gl:
        md.append(f"| {g['id']} | {g['title']} | {g.get('procedure_section','')} | {g.get('difficulty','')} |")
    with open(os.path.join(ROOT, "CLIENT_INDEX.md"), "w") as fh:
        fh.write("\n".join(md) + "\n")
    print(f"summarize: {len(rows)} clients, {len(gl)} gotchas")
    software_matrix(keys)


def software_matrix(keys):
    """v2: client x workbook-tab matrix + ProConnect items, and all_software_exceptions.jsonl."""
    tabs = [f"{n}." for n in range(3, 25)]
    allx, mat = [], []
    for k in keys:
        try:
            d = json.load(open(k))
        except Exception:
            continue
        xs = d.get("software_exceptions") or []
        for x in xs:
            allx.append(dict(client_id=d["client_id"], **x))
        used = {x["workbook_tab"].split(" ")[0] for x in xs}
        pc = [x for x in xs if x.get("tab_key") == "PC"]
        silent = sum(1 for x in xs if x.get("axcess_diagnostic") == "None - silent")
        mat.append((d["client_id"], d["client"], used, len(xs), silent, len(pc)))
    with open(os.path.join(ROOT, "answer_key", "all_software_exceptions.jsonl"), "w") as fh:
        for x in allx:
            fh.write(json.dumps(x, default=str) + "\n")
    hdr = "| Client | " + " | ".join(t.rstrip(".") for t in tabs) + " | Log-only | PC-only | Total | Silent |"
    md = ["# Software Exception Matrix - CCH Axcess workbook tabs x clients (v2)", "",
          "*Auto-generated by `generator/summarize.py`. Columns 3-24 are the firm's CCH Axcess 1040 Exception Workbook tabs; "
          "'Log-only' = Diagnostics Log item with no calc tab; 'PC-only' = Intuit ProConnect-specific exception; 'Silent' = no "
          "software diagnostic fires (the wrong answer calculates quietly).*", "", hdr,
          "|---|" + "---:|" * (len(tabs) + 4)]
    cover = {t: 0 for t in tabs}
    for cid, name, used, n, silent, npc in mat:
        cells = []
        for t in tabs:
            hit = t in used
            cover[t] += hit
            cells.append("X" if hit else "")
        md.append(f"| {cid} {name} | " + " | ".join(cells) + f" | {'X' if '2.' in used else ''} | {npc or ''} | {n} | {silent} |")
    md.append("| **Clients per tab** | " + " | ".join(str(cover[t]) for t in tabs) + " | | | | |")
    missing = [t for t in tabs if not cover[t]]
    md += ["", f"Total software exceptions: **{len(allx)}** across {len(mat)} clients "
           f"({sum(m[4] for m in mat)} silent, {sum(m[5] for m in mat)} ProConnect-only).",
           "", "Tabs not yet exercised: " + (", ".join(missing) if missing else "none - every workbook tab 3-24 is covered.")]
    pcx = [x for x in allx if x.get("proconnect_reference")]
    md += ["", "## ProConnect items with an Intuit reference", "", "| ID | Exception | Reference |", "|---|---|---|"]
    for x in pcx:
        md.append(f"| {x['id']} | {x['title']} | {x['proconnect_reference']} |")
    with open(os.path.join(ROOT, "SOFTWARE_EXCEPTION_MATRIX.md"), "w") as fh:
        fh.write("\n".join(md) + "\n")
    print(f"summarize: {len(allx)} software exceptions")


run()
