"""Rebuild data-set level index files from every client's Answer_Key.json.

Outputs (repo root of the data set):
  answer_key/summary.csv        one row per client with the key 1040 lines
  answer_key/all_gotchas.jsonl  every rubric item, one per line (for eval harnesses)
  CLIENT_INDEX.md               human-readable roster + gotcha counts + key numbers
"""
import csv
import glob
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, ".."))


def run():
    keys = sorted(glob.glob(os.path.join(ROOT, "clients", "*", "2025", "*_Answer_Key.json")))
    rows, gl = [], []
    for k in keys:
        try:
            d = json.load(open(k))
        except Exception as e:  # keep building even if one client is mid-write
            print("skip", k, e)
            continue
        s = d.get("form_1040_summary", {})
        rows.append({
            "client_id": d["client_id"], "client": d["client"], "filing_status": d.get("filing_status"),
            "state": d.get("facts_summary", {}).get("residence", ""),
            "agi_11": s.get("11"), "deduction_12e": s.get("12e"), "deduction_type": d.get("deduction_type"),
            "qbi_13a": s.get("13a"), "sch1a_13b": s.get("13b"), "taxable_income_15": s.get("15"),
            "tax_16": s.get("16"), "total_tax_24": s.get("24"), "payments_33": s.get("33"),
            "refund": d.get("refund"), "balance_due": d.get("balance_due"), "gotchas": len(d.get("gotchas", [])),
            "folder": os.path.relpath(os.path.dirname(os.path.dirname(k)), ROOT),
        })
        for g in d.get("gotchas", []):
            gl.append(dict(client_id=d["client_id"], **g))
    os.makedirs(os.path.join(ROOT, "answer_key"), exist_ok=True)
    if rows:
        with open(os.path.join(ROOT, "answer_key", "summary.csv"), "w", newline="") as fh:
            w = csv.DictWriter(fh, fieldnames=list(rows[0].keys()))
            w.writeheader()
            w.writerows(rows)
    with open(os.path.join(ROOT, "answer_key", "all_gotchas.jsonl"), "w") as fh:
        for g in gl:
            fh.write(json.dumps(g) + "\n")
    md = ["# Client Index - Project Evergreen Synthetic Data Set v1 (TY2025)", "",
          "*Auto-generated by `generator/summarize.py` from each client's Answer Key. Synthetic data.*", "",
          "| ID | Client | Status | Residence | AGI | Taxable income | Total tax | Refund | Balance due | Gotchas | Folder |",
          "|---|---|---|---|---:|---:|---:|---:|---:|---:|---|"]
    f = lambda x: f"{x:,}" if isinstance(x, (int, float)) else (x or "")
    for r in rows:
        md.append(f"| {r['client_id']} | {r['client']} | {r['filing_status']} | {r['state']} | {f(r['agi_11'])} | "
                  f"{f(r['taxable_income_15'])} | {f(r['total_tax_24'])} | {f(r['refund'])} | {f(r['balance_due'])} | "
                  f"{r['gotchas']} | [`{r['folder']}`]({r['folder']}) |")
    # gotcha by procedure section
    by = {}
    for g in gl:
        sec = g.get("procedure_section", "").split(" - ")[0].split(" (")[0].strip() or "Other"
        by.setdefault(sec, []).append(g["id"])
    md += ["", f"## Gotchas by procedure area ({len(gl)} total)", "", "| Procedure area | Count | Rubric IDs |", "|---|---:|---|"]
    for sec in sorted(by, key=lambda s: (-len(by[s]), s)):
        md.append(f"| {sec} | {len(by[sec])} | {', '.join(by[sec])} |")
    md += ["", "## All gotchas", "", "| ID | Title | Procedure section | Difficulty |", "|---|---|---|---|"]
    for g in gl:
        md.append(f"| {g['id']} | {g['title']} | {g.get('procedure_section','')} | {g.get('difficulty','')} |")
    with open(os.path.join(ROOT, "CLIENT_INDEX.md"), "w") as fh:
        fh.write("\n".join(md) + "\n")
    print(f"summarize: {len(rows)} clients, {len(gl)} gotchas")


run()
